WITH a
AS
(
SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
FROM FOOD_ORDER
WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY PRODUCT_ID
)

SELECT a.PRODUCT_ID, a.PRODUCT_NAME,
  (a.PRICE * b.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS a
JOIN a b
ON a.PRODUCT_ID = b.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID
