SELECT YEAR(sales_date) AS YEAR,
  MONTH(sales_date) AS MONTH,
  GENDER,
  COUNT(DISTINCT a.USER_ID) AS USERS
FROM USER_INFO AS a
JOIN ONLINE_SALE AS b
ON(a.USER_ID = b.USER_ID)
WHERE GENDER IS NOT NULL
GROUP BY 1,2,3
ORDER BY 1,2
