SELECT DATE_FORMAT(b.SALES_DATE, '%Y') AS YEAR,
       DATE_FORMAT(b.SALES_DATE, '%m') AS MONTH,
       COUNT(DISTINCT b.USER_ID) AS PUCHASED_USERS,
       ROUND(COUNT(DISTINCT b.USER_ID) 
             / (SELECT COUNT(USER_ID)
                FROM USER_INFO
                WHERE DATE_FORMAT(JOINED, '%Y') = '2021'), 1) AS PUCHASED_RATIO
FROM USER_INFO a
JOIN ONLINE_SALE b
ON (a.USER_ID = b.USER_ID) 
WHERE DATE_FORMAT(a.JOINED, '%Y') = '2021'
GROUP BY 1,2
