SELECT a.CATEGORY, a.MAX_PRICE, b.PRODUCT_NAME
FROM
  (
  SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
  FROM FOOD_PRODUCT
  GROUP BY 1
  ) AS a
JOIN FOOD_PRODUCT b
ON a.CATEGORY = b.CATEGORY
AND a.MAX_PRICE = b.PRICE
WHERE a.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC
