SELECT a.FOOD_TYPE, b.REST_ID, b.REST_NAME, b.FAVORITES
FROM
  (
  SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
  FROM REST_INFO
  GROUP BY 1
  ) a
JOIN REST_INFO b
ON a.FOOD_TYPE = b.FOOD_TYPE
WHERE a.MAX_FAVORITES = b.FAVORITES
ORDER BY 1 DESC
