SELECT APNT_NO, PT_NAME, a.PT_NO, a.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT a
JOIN PATIENT b
ON a.PT_NO = b.PT_NO
JOIN DOCTOR c
ON a.MDDR_ID = c.DR_ID
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
  AND APNT_CNCL_YN = 'N'
  AND a.MCDP_CD = 'CS'
ORDER BY APNT_YMD
